items:
    - 'ACACIA_FENCE'
    - 'ACACIA_FENCE_GATE'
    - 'ACACIA_STAIRS'
    - 'ACTIVATOR_RAIL'
    - 'ANVIL'
    - 'APPLE'
    - 'ARROW'
    - 'BAKED_POTATO'
    - 'BEACON'
    - 'BED'
    - 'BIRCH_FENCE'
    - 'BIRCH_FENCE_GATE'
    - 'BIRCH_WOOD_STAIRS'
    - 'BLAZE_POWDER'
    - 'BLAZE_ROD'
    - 'BOAT'
    - 'BONE'
    - 'BOOK'
    - 'BOOK_AND_QUILL'
    - 'BOOKSHELF'
    - 'BOW'
    - 'BOWL'
    - 'BREAD'
    - 'BREWING_STAND_ITEM'
    - 'BRICK'
    - 'BRICK_STAIRS'
    - 'BROWN_MUSHROOM'
    - 'BUCKET'
    - 'CACTUS'
    - 'CAKE'
    - 'CARPET'
    - 'CARROT_STICK'
    - 'CHAINMAIL_BOOTS'
    - 'CHAINMAIL_CHESTPLATE'
    - 'CHAINMAIL_HELMET'
    - 'CHAINMAIL_LEGGINGS'
    - 'CHEST'
    - 'CLAY'
    - 'COAL'
    - 'COAL_BLOCK'
    - 'COAL_ORE'
    - 'COBBLE_WALL'
    - 'COBBLESTONE'
    - 'COBBLESTONE_STAIRS'
    - 'COMPASS'
    - 'COOKED_BEEF'
    - 'COOKED_CHICKEN'
    - 'COOKED_FISH'
    - 'COOKED_MUTTON'
    - 'COOKED_RABBIT'
    - 'COOKIE'
    - 'DARK_OAK_FENCE'
    - 'DARK_OAK_FENCE_GATE'
    - 'DARK_OAK_STAIRS'
    - 'DEAD_BUSH'
    - 'DETECTOR_RAIL'
    - 'DIAMOND'
    - 'DIAMOND_AXE'
    - 'DIAMOND_BARDING'
    - 'DIAMOND_BLOCK'
    - 'DIAMOND_BOOTS'
    - 'DIAMOND_CHESTPLATE'
    - 'DIAMOND_HELMET'
    - 'DIAMOND_HOE'
    - 'DIAMOND_LEGGINGS'
    - 'DIAMOND_ORE'
    - 'DIAMOND_PICKAXE'
    - 'DIAMOND_SPADE'
    - 'DIAMOND_SWORD'
    - 'DIRT'
    - 'DISPENSER'
    - 'DROPPER'
    - 'EGG'
    - 'EMERALD'
    - 'EMERALD_BLOCK'
    - 'EMERALD_ORE'
#    - 'ENCHANTED_BOOK'
    - 'ENCHANTMENT_TABLE'
    - 'ENDER_CHEST'
    - 'ENDER_PEARL'
    - 'EXP_BOTTLE'
    - 'EXPLOSIVE_MINECART'
    - 'FEATHER'
    - 'FENCE'
    - 'FENCE_GATE'
    - 'FISHING_ROD'
    - 'FLINT'
    - 'FLINT_AND_STEEL'
    - 'FLOWER_POT_ITEM'
    - 'FURNACE'
    - 'GHAST_TEAR'
    - 'GLASS'
    - 'GLASS_BOTTLE'
    - 'GLOWSTONE'
    - 'GLOWSTONE_DUST'
    - 'GOLD_AXE'
    - 'GOLD_BARDING'
    - 'GOLD_BLOCK'
    - 'GOLD_BOOTS'
    - 'GOLD_CHESTPLATE'
    - 'GOLD_HELMET'
    - 'GOLD_HOE'
    - 'GOLD_INGOT'
    - 'GOLD_LEGGINGS'
    - 'GOLD_NUGGET'
    - 'GOLD_ORE'
    - 'GOLD_PICKAXE'
    - 'GOLD_PLATE'
    - 'GOLD_SPADE'
    - 'GOLD_SWORD'
    - 'GOLDEN_APPLE'
    - 'GOLDEN_CARROT'
    - 'GRAVEL'
    - 'GRILLED_PORK'
    - 'HAY_BLOCK'
    - 'HOPPER'
    - 'HOPPER_MINECART'
    - 'ICE'
    - 'INK_SACK'
    - 'IRON_AXE'
    - 'IRON_BARDING'
    - 'IRON_BLOCK'
    - 'IRON_BOOTS'
    - 'IRON_CHESTPLATE'
    - 'IRON_DOOR'
    - 'IRON_FENCE'
    - 'IRON_HELMET'
    - 'IRON_HOE'
    - 'IRON_INGOT'
    - 'IRON_LEGGINGS'
    - 'IRON_ORE'
    - 'IRON_PICKAXE'
    - 'IRON_PLATE'
    - 'IRON_SPADE'
    - 'IRON_SWORD'
    - 'IRON_TRAPDOOR'
    - 'ITEM_FRAME'
    - 'JACK_O_LANTERN'
    - 'JUKEBOX'
    - 'JUNGLE_FENCE'
    - 'JUNGLE_FENCE_GATE'
    - 'JUNGLE_WOOD_STAIRS'
    - 'LADDER'
    - 'LAPIS_BLOCK'
    - 'LAPIS_ORE'
    - 'LAVA_BUCKET'
    - 'LEASH'
    - 'LEATHER'
    - 'LEATHER_BOOTS'
    - 'LEATHER_CHESTPLATE'
    - 'LEATHER_HELMET'
    - 'LEATHER_LEGGINGS'
    - 'LEAVES'
    - 'LEVER'
    - 'LOG'
    - 'MAGMA_CREAM'
    - 'MELON'
    - 'MELON_BLOCK'
    - 'MELON_SEEDS'
    - 'MILK_BUCKET'
    - 'MINECART'
    - 'MOSSY_COBBLESTONE'
    - 'MUSHROOM_SOUP'
    - 'NAME_TAG'
    - 'NETHER_BRICK'
    - 'NETHER_BRICK_STAIRS'
    - 'NETHER_FENCE'
    - 'NETHER_STAR'
    - 'NETHER_STALK'
    - 'NETHERRACK'
    - 'NOTE_BLOCK'
    - 'OBSIDIAN'
    - 'PAPER'
    - 'POWERED_RAIL'
    - 'PRISMARINE'
    - 'PRISMARINE_CRYSTALS'
    - 'PRISMARINE_SHARD'
    - 'PUMPKIN'
    - 'PUMPKIN_PIE'
    - 'QUARTZ'
    - 'QUARTZ_BLOCK'
    - 'QUARTZ_ORE'
    - 'QUARTZ_STAIRS'
    - 'RABBIT_FOOT'
    - 'RABBIT_HIDE'
    - 'RABBIT_STEW'
    - 'RECORD_10'
    - 'RECORD_11'
    - 'RECORD_12'
    - 'RECORD_3'
    - 'RECORD_4'
    - 'RECORD_5'
    - 'RECORD_6'
    - 'RECORD_7'
    - 'RECORD_8'
    - 'RECORD_9'
    - 'RED_SANDSTONE'
    - 'RED_SANDSTONE_STAIRS'
    - 'REDSTONE'
    - 'REDSTONE_BLOCK'
    - 'REDSTONE_ORE'
    - 'ROTTEN_FLESH'
    - 'SADDLE'
    - 'SAND'
    - 'SANDSTONE'
    - 'SANDSTONE_STAIRS'
    - 'SAPLING'
    - 'SEA_LANTERN'
    - 'SEEDS'
    - 'SHEARS'
    - 'SIGN'
    - 'SLIME_BALL'
    - 'SLIME_BLOCK'
    - 'SMOOTH_BRICK'
    - 'SMOOTH_STAIRS'
    - 'SNOW_BALL'
    - 'SNOW_BLOCK'
    - 'SOUL_SAND'
    - 'SPECKLED_MELON'
    - 'SPIDER_EYE'
    - 'SPONGE'
    - 'SPRUCE_FENCE'
    - 'SPRUCE_FENCE_GATE'
    - 'SPRUCE_WOOD_STAIRS'
    - 'STAINED_CLAY'
    - 'STAINED_GLASS'
    - 'STAINED_GLASS_PANE'
    - 'STICK'
    - 'STONE'
    - 'STONE_AXE'
    - 'STONE_BUTTON'
    - 'STONE_HOE'
    - 'STONE_PICKAXE'
    - 'STONE_PLATE'
    - 'STONE_SPADE'
    - 'STONE_SWORD'
    - 'STRING'
    - 'SUGAR'
    - 'SUGAR_CANE'
    - 'TNT'
    - 'TORCH'
    - 'TRAPPED_CHEST'
    - 'VINE'
    - 'WATCH'
    - 'WATER_BUCKET'
    - 'WATER_LILY'
    - 'WEB'
    - 'WOOD'
    - 'WOOD_AXE'
    - 'WOOD_BUTTON'
    - 'WOOD_HOE'
    - 'WOOD_PICKAXE'
    - 'WOOD_PLATE'
    - 'WOOD_SPADE'
    - 'WOOD_STAIRS'
    - 'WOOD_STEP'
    - 'WOOD_SWORD'
    - 'WOOL'
    - 'WORKBENCH'